---

  - name: Download Hashicorp Vault with SHA verification
    get_url: 
      url: "https://releases.hashicorp.com/vault/{{ hashi_vault_version }}/vault_{{ hashi_vault_version }}_linux_amd64.zip"
      dest: /tmp/
      checksum: sha256:"{{ hashi_vault_checksum }}"

  - name: Install Unzip package
    apt:
      name: unzip
      state: latest
      update_cache: yes

  - name: Unzip Hashicorp Vault
    unarchive:
      src: "/tmp/vault_{{ hashi_vault_version }}_linux_amd64.zip"
      dest: /usr/local/bin/
      remote_src: yes

  - name: Enable Hashicorp Vault auto-complete install in .bashrc if it doesn't already exist
    command: vault -autocomplete-install
    ignore_errors: true

  - name: Add the Vault system user
    user:
      name: vault
      comment: System user account for Hashicorp Vault
      home: /etc/vault
      shell: /bin/false
      system: yes
      append: yes

  - name: Create vault directory in /etc/ for Hashicorp Vault
    file:
      path: /etc/vault
      state: directory
      owner: vault
      group: vault
      mode: '0755'

  - name: Recursively create vault directories in /var/lib/ for Hashicorp Vault
    file:
      path: /var/lib/vault/data
      state: directory
      owner: vault
      group: vault
      mode: '0755'

  - name: Copy Hashicorp Vault service configuration
    copy:
      src: vault.service
      dest: /etc/systemd/system/
      owner: root
      group: root
      mode: '0755'

  - name: Copy Hashicorp Vault config.hcl configuration
    copy:
      src: config.hcl
      dest: /etc/vault/
      owner: vault
      group: vault
      mode: '0755'

  - name: Reload systemd daemon
    systemd:
      daemon_reload: yes

  - name: Enable and start vault.service
    systemd:
      name: vault.service
      enabled: yes
      state: started

  - name: Export Hashicorp Vault URL
    shell: "export VAULT_ADDR=http://{{ ansible_default_ipv4.address }}:8200"

  - name: Export Hashicorp Vault URL
    shell: echo "export VAULT_ADDR=http://{{ ansible_default_ipv4.address }}:8200" >> ~/.bashrc"